#include-once

#Region - Chilkat_Email.au3 - Header
; Title .........: Chilkat_Email.au3
; Language ......: English
; Description ...: Email, mail transport and message-format support.
; Author ........: mLipok
; Modified ......: AI / mLipok
; Date ..........: 2026/07/13
; Version .......: v0.3.0 BETA - Work in progress
; Remarks .......: This module is linked and loaded by Chilkat.au3.
; Categories ....: DKIM / DomainKey; Email Object; GMail REST API; GMail SMTP/IMAP/POP; IMAP; MHT / HTML Email; MIME; Office365; Outlook; Outlook Calendar; Outlook Contact; POP3; SMTP
#EndRegion - Chilkat_Email.au3 - Header

#Region ; _Chilkat_IMAP_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_IMAP_ObjCreate
; Description ...: Creates a Chilkat Imap COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_IMAP_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Imap object was introduced in version 9.5.0.26.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatImapRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_IMAP_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_IMAP)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_IMAP_ObjCreate

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_IMAP_ApendEmail
; Description ...: Appends a Chilkat Email object to the selected IMAP mailbox.
; Syntax ........: _Chilkat_IMAP_ApendEmail(ByRef $oIMAP, ByRef $oEmail, $sMailbox_name = "Inbox.Sent")
; Parameters ....: $oIMAP                 - [in/out] Chilkat Imap object.
;                  $oEmail                - [in/out] Chilkat Email object.
;                  $sMailbox_name         - [in] IMAP mailbox name. Default is "Inbox.Sent".
; Return values .: Success: Chilkat AppendMail result. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI - Name keeps the current UDF spelling for compatibility.
; Related .......: __Chilkat_ConsoleWrite_IFNC, _Chilkat_IMAP_ListMailboxes, __Chilkat_LogOnError, __Chilkat_Log
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_IMAP_ApendEmail(ByRef $oIMAP, ByRef $oEmail, $sMailbox_name = "Inbox.Sent")
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	; https://www.example-code.com/autoit/sendWithCopyToSentMailbox.asp
	#CS
	'  The AppendMail method uploads an email to an IMAP server
	'  and saves it in the mailbox specified:
	success = imap.AppendMail("Inbox.Sent",email)
	If (success <> 1) Then
		__Chilkat_ConsoleWrite_IFNC(imap.LastErrorText)
		WScript.Quit
	End If
	#CE
;~ _Log_Info(@ScriptLineNumber & ' IMAP sent: ListMailboxes::' )
;~ 	_log(_Chilkat_IMAP_ListMailboxes($oIMAP, '', '*'))

	Local $iSuccess = $oIMAP.AppendMail($sMailbox_name, $oEmail)
;~ _Log_Info(@ScriptLineNumber & ' IMAP sent: ' & $sMailbox_name & '  == '  & $iSuccess & ' :: ' & $oIMAP.AppendUid)
	If @error Or $iSuccess <> 1 Then
		If $sMailbox_name = 'INBOX.Sent' Then
			$sMailbox_name = 'Sent'
			$oIMAP.AppendMail($sMailbox_name, $oEmail)
;~ _Log_Info(@ScriptLineNumber & ' IMAP sent: ' & $sMailbox_name & '  == '  & $iSuccess & ' :: ' & $oIMAP.AppendUid)
			__Chilkat_LogOnError(@ScriptLineNumber & ' Changing: INBOX.Sent > Sent', $oIMAP)
		ElseIf $sMailbox_name = 'Sent' Then
			$sMailbox_name = 'INBOX.Sent'
			$oIMAP.AppendMail($sMailbox_name, $oEmail)
;~ _Log_Info(@ScriptLineNumber & ' IMAP sent: ' & $sMailbox_name & '  == '  & $iSuccess & ' :: ' & $oIMAP.AppendUid)
			__Chilkat_LogOnError(@ScriptLineNumber & ' Changing: Sent > INBOX.Sent', $oIMAP)
		EndIf
	EndIf
;~ _Log_Info(@ScriptLineNumber & ' IMAP sent')
	If @error Or $iSuccess <> 1 Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber & ' IMAP.AppendMail ', $oIMAP)
		Return SetError(@error, @extended, $iSuccess)
	EndIf

;~ _Log_Info(@ScriptLineNumber & ' IMAP sent')
	__Chilkat_Log(@ScriptLineNumber & " Mail saved to Mailbox=" & $sMailbox_name)
EndFunc   ;==>_Chilkat_IMAP_ApendEmail

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_IMAP_ConnectAndLogin
; Description ...: Creates a Chilkat Imap object, connects to an IMAP server, and logs in.
; Syntax ........: _Chilkat_IMAP_ConnectAndLogin($sIMAP_Login, $sIMAP_Password, $sIMAP_ServerName, $sIMAP_Port = 993)
; Parameters ....: $sIMAP_Login           - [in] optional IMAP login used for saving the sent message.
;                  $sIMAP_Password        - [in] optional IMAP password used for saving the sent message.
;                  $sIMAP_ServerName      - [in] IMAP server host name.
;                  $sIMAP_Port            - [in] IMAP server port. Default is 993.
; Return values .: Success: Chilkat Imap object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: _Chilkat_IMAP_ObjCreate, __Chilkat_ConsoleWrite_IFNC, __Chilkat_LogOnError
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_IMAP_ConnectAndLogin($sIMAP_Login, $sIMAP_Password, $sIMAP_ServerName, $sIMAP_Port = 993)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

;~ 	https://www.example-code.com/autoit/sendWithCopyToSentMailbox.asp
	Local $oIMAP = _Chilkat_IMAP_ObjCreate()
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	#CS
		'  Connect to an IMAP server.
		'  Use TLS
		imap.Ssl = 1
		imap.Port = 993
		success = imap.Connect("mail.mydomain.com")
		If (success <> 1) Then
			__Chilkat_ConsoleWrite_IFNC(imap.LastErrorText)
			WScript.Quit
		End If
	#CE
;~ 	$oIMAP.Ssl = 1
	$oIMAP.StartTLS = 1
	$oIMAP.Port = $sIMAP_Port
;~ 	$oIMAP.Port = 993

	Local $iSuccess = $oIMAP.Connect($sIMAP_ServerName)
	If @error Or $iSuccess <> 1 Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber & ' IMAP.Connect ', $oIMAP)
		Return SetError(@error, @extended, $iSuccess)
	EndIf

	#CS
	'  Login
	success = imap.Login("myLogin","myPassword")
	If (success <> 1) Then
		__Chilkat_ConsoleWrite_IFNC(imap.LastErrorText)
		WScript.Quit
	End If
	#CE
	$iSuccess = $oIMAP.Login($sIMAP_Login, $sIMAP_Password)
	If @error Or $iSuccess <> 1 Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber & ' IMAP.Login ', $oIMAP)
		Return SetError(@error, @extended, $iSuccess)
	EndIf

	Return $oIMAP
EndFunc   ;==>_Chilkat_IMAP_ConnectAndLogin

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_IMAP_GetSentMailboxName
; Description ...: Detects a usable Sent mailbox name for the connected IMAP account.
; Syntax ........: _Chilkat_IMAP_GetSentMailboxName(ByRef $oIMAP)
; Parameters ....: $oIMAP                 - [in/out] Chilkat Imap object.
; Return values .: Success: detected Sent mailbox name. Failure: sets @error/@extended and returns empty string.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header modified by #AI
; Related .......:
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_IMAP_GetSentMailboxName(ByRef $oIMAP)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler
	If $oIMAP.GetMailboxStatus('Sent') Then
		Return 'Sent'
	ElseIf $oIMAP.GetMailboxStatus('INBOX.Sent') Then
		Return 'INBOX.Sent'
	ElseIf $oIMAP.GetMailboxStatus('SENT') Then
		Return 'SENT'
	ElseIf $oIMAP.GetMailboxStatus('INBOX.SENT') Then
		Return 'INBOX.SENT'
	Else
		Return SetError($CHILKAT_ERR_UNKNOWN, 0, '')
	EndIf
EndFunc   ;==>_Chilkat_IMAP_GetSentMailboxName

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_IMAP_ListMailboxes
; Description ...: Lists IMAP mailboxes matching the supplied reference name and wildcard.
; Syntax ........: _Chilkat_IMAP_ListMailboxes(ByRef $oIMAP, $s_refName = '', $s_wildcardedMailbox = "*")
; Parameters ....: $oIMAP                 - [in/out] Chilkat Imap object.
;                  $s_refName             - [in] IMAP reference name. Default is ''.
;                  $s_wildcardedMailbox   - [in] IMAP wildcard mailbox pattern. Default is "*".
; Return values .: Success: Chilkat Mailboxes object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: _Chilkat_ObjName_FlagsValue, __Chilkat_LogOnError, __Chilkat_ConsoleWrite_IFNC
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_IMAP_ListMailboxes(ByRef $oIMAP, $s_refName = '', $s_wildcardedMailbox = "*")
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

;~ 	https://www.example-code.com/autoit/imap_listMailboxes.asp
	; The ListMailboxes method returns a Mailboxes object
	; that contains the collection of mailboxes.
	; It accepts two arguments: a $s_refName and a $s_wildcardedMailbox.

	; $s_refName is usually set to an empty string.
	; A non-empty reference name argument is the name of a mailbox or a level of
	; mailbox hierarchy, and indicates the context in which the mailbox
	; name is interpreted.

	; Select all mailboxes matching this pattern:  $s_wildcardedMailbox = "*"

	; mboxes is a Chilkat_9_5_0.Mailboxes
	_Chilkat_ObjName_FlagsValue($oIMAP, @ScriptLineNumber)
	$oIMAP.VerboseLogging = 1
	Local $oMBoxes = $oIMAP.ListMailboxes($s_refName, $s_wildcardedMailbox)
	Local $iError = @error
	Local $iLMS = $oIMAP.LastMethodSuccess
	If $iError Or $iLMS = 0 Or IsObj($oMBoxes) = 0 Then
		__Chilkat_LogOnError(@ScriptLineNumber & ' Can not get Mailboxes')
		If Not @Compiled Then _Chilkat_ObjName_FlagsValue($oMBoxes, @ScriptLineNumber)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' _Chilkat_IMAP_ListMailboxes:')
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' $s_refName = ' & $s_refName)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' $s_wildcardedMailbox = ' & $s_wildcardedMailbox)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' LMS: ' & $iLMS)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' LRC: ' & $oIMAP.LastResponseCode)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' LIR: ' & $oIMAP.LastIntermediateResponse)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' SM: ' & $oIMAP.SelectedMailbox)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' SL: ' & $oIMAP.SessionLog)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' TLSV: ' & $oIMAP.TlsVersion)
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' ' & 'IsObj($oMBoxes)=' & IsObj($oMBoxes))
		__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' ' & 'VarGetType($oMBoxes)=' & VarGetType($oMBoxes))
		$oIMAP.VerboseLogging = 0
;~ 		Return SetError($CHILKAT_ERR_GENERAL, @extended, $oMBoxes)

	EndIf
	$oIMAP.VerboseLogging = 0

	Local $s_ListOfMBoxes = ''
	For $iMBox_idx = 0 To $oMBoxes.Count
		$s_ListOfMBoxes &= $oMBoxes.GetName($iMBox_idx) & @CRLF
	Next

	__Chilkat_ConsoleWrite_IFNC(@ScriptLineNumber & ' _Chilkat_IMAP_ListMailboxes: $s_ListOfMBoxes:' & @CRLF & $s_ListOfMBoxes)
	Return $s_ListOfMBoxes

EndFunc   ;==>_Chilkat_IMAP_ListMailboxes

#EndRegion ; _Chilkat_IMAP_**

#Region ; _Chilkat_MAILBOXES_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_MAILBOXES_ObjCreate
; Description ...: Creates a Chilkat Mailboxes COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_MAILBOXES_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Mailboxes object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatMailboxesRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_MAILBOXES_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_MAILBOXES)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_MAILBOXES_ObjCreate

#EndRegion ; _Chilkat_MAILBOXES_**

#Region ; _Chilkat_MAILMAN_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_MAILMAN_ObjCreate
; Description ...: Creates and optionally initializes a Chilkat MailMan object for SMTP sending.
; Syntax ........: _Chilkat_MAILMAN_ObjCreate($s_Username = '', $s_Password = '', $s_SmtpServer = '', $s_SMTP_PORT = 465, $s_SSL = 1)
; Parameters ....: $s_Username            - [in] SMTP username. Default is ''.
;                  $s_Password            - [in] SMTP password. Default is ''.
;                  $s_SmtpServer          - [in] SMTP server host name. Default is ''.
;                  $s_SMTP_PORT           - [in] SMTP server port. Default is 465.
;                  $s_SSL                 - [in] flag enabling SMTP SSL/TLS. Default is 1.
; Return values .: Success: Chilkat MailMan object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat MailMan object was introduced in version 9.5.0.49.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatMailManRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_MAILMAN_ObjCreate($s_Username = '', $s_Password = '', $s_SmtpServer = '', $s_SMTP_PORT = 465, $s_SSL = 1)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	Local $oMailMan = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_MAILMAN)
	If @error Then Return SetError(@error, @extended, $oMailMan)

	If $s_Username = '' Then Return SetError(@error, @extended, $oMailMan)

	;  Set the SMTP server.
	$oMailMan.SmtpHost = $s_SmtpServer
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	;  Set the SMTP login/password (if required)
	$oMailMan.SmtpUsername = $s_Username
	$oMailMan.SmtpPassword = $s_Password

	;  Connect to SMTP port 465 using TLS.
	$oMailMan.SmtpPort = $s_SMTP_PORT
;~ 	$oMailMan.SmtpSsl = $s_SSL
	$oMailMan.StartTLS = $s_SSL

	Return SetError(@error, @extended, $oMailMan)
EndFunc   ;==>_Chilkat_MAILMAN_ObjCreate

#EndRegion ; _Chilkat_MAILMAN_**

#Region ; _Chilkat_EMAIL_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_EMAIL_ObjCreate
; Description ...: Creates and optionally initializes a Chilkat Email object.
; Syntax ........: _Chilkat_EMAIL_ObjCreate($s_FromAddress = '', $s_ToAddress = '', $s_Subject = '', $s_Body = '', $s_ReplyTo = '', $i_Importance = 3, $s_UserAgent = @ScriptName, $s_Charset = 'utf-8')
; Parameters ....: $s_FromAddress         - [in] sender email address. Default is ''.
;                  $s_ToAddress           - [in] recipient email address list separated by commas. Default is ''.
;                  $s_Subject             - [in] email subject. Default is ''.
;                  $s_Body                - [in] email body. Default is ''.
;                  $s_ReplyTo             - [in] Reply-To address. Default is ''.
;                  $i_Importance          - [in] email importance value. Default is 3.
;                  $s_UserAgent           - [in] User-Agent header value stored in the email object. Default is @ScriptName.
;                  $s_Charset             - [in] email charset value. Default is 'utf-8'.
; Return values .: Success: Chilkat Email object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Email object was introduced in version 9.5.0.57.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatEmailRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_EMAIL_ObjCreate($s_FromAddress = '', $s_ToAddress = '', $s_Subject = '', $s_Body = '', $s_ReplyTo = '', $i_Importance = 3, $s_UserAgent = @ScriptName, $s_Charset = 'utf-8')
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	Local $oEmail = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_EMAIL)
	If @error Then Return SetError(@error, @extended, $oEmail)

	If $s_FromAddress = '' Then Return SetError(@error, @extended, $oEmail)

	$oEmail.Subject = $s_Subject

	Local $a_ToAddress = StringSplit($s_ToAddress, ',')
	For $iEmail_idx = 1 To $a_ToAddress[0]
		$oEmail.AddTo("", $a_ToAddress[$iEmail_idx])
	Next

	$oEmail.From = $s_FromAddress
	$oEmail.Body = $s_Body
	$oEmail.Charset = $s_Charset
	;  To add more recipients, call AddTo, AddCC, or AddBcc once per recipient.

	Switch $i_Importance
		Case 1
			$oEmail.AddHeaderField("X-Priority", "1 (High)")
		Case 3
			$oEmail.AddHeaderField("X-Priority", "3 (Normal)")
		Case 5
			$oEmail.AddHeaderField("X-Priority", "5 (Low)")
		Case Else
			$oEmail.AddHeaderField("X-Priority", "3 (Normal)")
	EndSwitch
	$oEmail.AddHeaderField("User-Agent", $s_UserAgent)

	$oEmail.ReplyTo = $s_ReplyTo ; Sets the "Reply-To" header field to the specified email address.
	$oEmail.ReturnReceipt = 0 ; Set to 1 if you want the email to request a return-receipt when received by the recipient. The default value is 0.

	Return SetError(@error, @extended, $oEmail)
EndFunc   ;==>_Chilkat_EMAIL_ObjCreate

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_EMAIL_AddFileAttachment
; Description ...: Adds one or more file attachments to a Chilkat Email object.
; Syntax ........: _Chilkat_EMAIL_AddFileAttachment(ByRef $oEmail, $s_Attachments)
; Parameters ....: $oEmail                - [in/out] Chilkat Email object.
;                  $s_Attachments         - [in] semicolon-separated attachment list or a one-column array.
; Return values .: Success: no explicit return. Failure: sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: __Chilkat_LogOnError
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_EMAIL_AddFileAttachment(ByRef $oEmail, $s_Attachments)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler
	;  Add some attachments.
	;  The AddFileAttachment method returns the value of the content-type it chose for the attachment.

	Local $a_Attachment_FilesList
	If IsString($s_Attachments) Then
		$a_Attachment_FilesList = StringSplit($s_Attachments, ';')
	ElseIf UBound($s_Attachments, $UBOUND_ROWS) And UBound($s_Attachments, $UBOUND_COLUMNS) = 1 Then
		$a_Attachment_FilesList = $s_Attachments
	ElseIf $s_Attachments = Default Then
		; @TODO ?
	Else
		; @TODO ?
	EndIf

	If Not ($s_Attachments = Default Or $s_Attachments = '') Then
		Local $iContentType
		#forceref $iContentType
		For $iAttachment_idx = 1 To $a_Attachment_FilesList[0]
			$iContentType = $oEmail.AddFileAttachment($a_Attachment_FilesList[$iAttachment_idx])
			If @error Or ($oEmail.LastMethodSuccess <> 1) Then
				If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
				__Chilkat_LogOnError(@ScriptLineNumber & ' AddFileAttachment: ' & $a_Attachment_FilesList[$iAttachment_idx], $oEmail)
				Return ; @TODO - refactoring
			EndIf
		Next
	EndIf
EndFunc   ;==>_Chilkat_EMAIL_AddFileAttachment

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_EMAIL_SendEmail
; Description ...: Sends a prepared Chilkat Email object by using a Chilkat MailMan object.
; Syntax ........: _Chilkat_EMAIL_SendEmail(ByRef $oMailMan, ByRef $oEmail)
; Parameters ....: $oMailMan              - [in/out] Chilkat MailMan object.
;                  $oEmail                - [in/out] Chilkat Email object.
; Return values .: Success: no explicit return. Failure: returns Chilkat failure value and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: __Chilkat_LogOnError
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_EMAIL_SendEmail(ByRef $oMailMan, ByRef $oEmail)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	;  Call SendEmail to connect to the SMTP server and send.
	;  The connection (i.e. session) to the SMTP server remains open
	;  so that subsequent SendEmail calls may use the same connection.
	Local $iSuccess = $oMailMan.SendEmail($oEmail)
	If @error Or $iSuccess <> 1 Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber & ' MailMan.SendEmail ', $oMailMan)
		Return SetError(@error, @extended, $iSuccess)
;~ 		Return SetError($CHILKAT_ERR_MAILMAN_0, @extended, $CHILKAT_RET_FAILURE) ; @TODO - refactoring
	EndIf

	Return ; @TODO - refactoring ?
EndFunc   ;==>_Chilkat_EMAIL_SendEmail

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_EMAIL_SendSingleMail
; Description ...: Builds and sends one email, with optional attachments, EML save, and IMAP Sent copy.
; Syntax ........: _Chilkat_EMAIL_SendSingleMail($s_From_CommonName, $s_FromAddress, $s_ToAddress, $s_Subject, $s_Body, $s_Attachments, $s_ReplyTo, $s_Username, $s_Password, $s_SmtpServer, $s_SMTP_PORT = 465, $s_SSL = 1, $i_Importance = 3, $s_UserAgent = @ScriptName, $sIMAP_Login = '', $sIMAP_Password = '', $sIMAP_ServerName = '', $sIMAP_Port = 993, $s_Sent_Mailbox_Name = Default, $s_SaveEML_FFP = '')
; Parameters ....: $s_From_CommonName     - [in] sender display name.
;                  $s_FromAddress         - [in] sender email address.
;                  $s_ToAddress           - [in] recipient email address list separated by commas.
;                  $s_Subject             - [in] email subject.
;                  $s_Body                - [in] email body.
;                  $s_Attachments         - [in] semicolon-separated attachment list or a one-column array.
;                  $s_ReplyTo             - [in] Reply-To address.
;                  $s_Username            - [in] SMTP username.
;                  $s_Password            - [in] SMTP password.
;                  $s_SmtpServer          - [in] SMTP server host name.
;                  $s_SMTP_PORT           - [in] SMTP server port. Default is 465.
;                  $s_SSL                 - [in] flag enabling SMTP SSL/TLS. Default is 1.
;                  $i_Importance          - [in] email importance value. Default is 3.
;                  $s_UserAgent           - [in] User-Agent header value stored in the email object. Default is @ScriptName.
;                  $sIMAP_Login           - [in] optional IMAP login used for saving the sent message. Default is ''.
;                  $sIMAP_Password        - [in] optional IMAP password used for saving the sent message. Default is ''.
;                  $sIMAP_ServerName      - [in] IMAP server host name. Default is ''.
;                  $sIMAP_Port            - [in] IMAP server port. Default is 993.
;                  $s_Sent_Mailbox_Name   - [in] optional Sent mailbox name; Default auto-detects it.
;                  $s_SaveEML_FFP         - [in] optional full path where the generated EML is saved. Default is ''.
; Return values .: Success: MIME binary data. Failure: $CHILKAT_RET_FAILURE or empty string and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: _Chilkat_MAILMAN_ObjCreate, __Chilkat_LogOnError, _Chilkat_EMAIL_ObjCreate, _Chilkat_EMAIL_AddFileAttachment, _Chilkat_EMAIL_SendEmail, __Chilkat_Log, __Chilkat_ConsoleWrite_IFNC, _Chilkat_IMAP_ConnectAndLogin, _Chilkat_IMAP_GetSentMailboxName, _Chilkat_IMAP_ApendEmail
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_EMAIL_SendSingleMail($s_From_CommonName, $s_FromAddress, $s_ToAddress, $s_Subject, $s_Body, $s_Attachments, $s_ReplyTo, $s_Username, $s_Password, $s_SmtpServer, $s_SMTP_PORT = 465, $s_SSL = 1, $i_Importance = 3, $s_UserAgent = @ScriptName, $sIMAP_Login = '', $sIMAP_Password = '', $sIMAP_ServerName = '', $sIMAP_Port = 993, $s_Sent_Mailbox_Name = Default, $s_SaveEML_FFP = '')

	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	If $s_Attachments <> '' And Not FileExists($s_Attachments) Then _
			Return SetError($CHILKAT_ERR_FILENOTEXIST, $CHILKAT_EXT_DEFAULT, $CHILKAT_RET_FAILURE)

	If IsString($s_From_CommonName) And StringLen($s_From_CommonName) > 0 Then
		$s_FromAddress = '"' & $s_From_CommonName & '" <' & $s_FromAddress & '>'
	Else
	EndIf

	Local $oMailMan = _Chilkat_MAILMAN_ObjCreate($s_Username, $s_Password, $s_SmtpServer, $s_SMTP_PORT, $s_SSL)
	__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail 1 ', $oMailMan)
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	;  Create a new email object
	Local $oEmail = _Chilkat_EMAIL_ObjCreate($s_FromAddress, $s_ToAddress, $s_Subject, $s_Body, $s_ReplyTo, $i_Importance, $s_UserAgent, 'utf-8')
	__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail  2', $oMailMan)
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	If $s_Attachments <> '' Then
		_Chilkat_EMAIL_AddFileAttachment($oEmail, $s_Attachments)
		__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail 3 ', $oMailMan)
		If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)
	EndIf

	_Chilkat_EMAIL_SendEmail($oMailMan, $oEmail)
	__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail 4 ', $oMailMan)
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)
	__Chilkat_Log(@ScriptLineNumber & ' Mail with attachments sent!')

	If $s_SaveEML_FFP <> '' Then
		__Chilkat_ConsoleWrite_IFNC('---> @error=' & @error & '  @extended=' & @extended & '  @ScriptLineNumber=' & @ScriptLineNumber & ' : IFNC: Chilkat.au3' & @CRLF)
		__Chilkat_LogOnError(@ScriptLineNumber & " Save result = " & $oEmail.SaveEML($s_SaveEML_FFP))
		__Chilkat_ConsoleWrite_IFNC('---> @error=' & @error & '  @extended=' & @extended & '  @ScriptLineNumber=' & @ScriptLineNumber & ' : IFNC: Chilkat.au3' & @CRLF)
	EndIf

	Local $vReturn = '', $iErr, $iExt
	If $sIMAP_Login <> '' Then
		Local $oIMAP = _Chilkat_IMAP_ConnectAndLogin($sIMAP_Login, $sIMAP_Password, $sIMAP_ServerName, $sIMAP_Port)
		__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail 5 ', $oMailMan)
		If @error Then Return SetError(@error, @extended, '')

		If $s_Sent_Mailbox_Name = Default Then $s_Sent_Mailbox_Name = _Chilkat_IMAP_GetSentMailboxName($oIMAP)
		__Chilkat_Log(@ScriptLineNumber & ' "SENT" Mailbox name = ' & $s_Sent_Mailbox_Name)
		$iErr = @error
		$iExt = @extended
		If Not @error Then
			$vReturn = _Chilkat_IMAP_ApendEmail($oIMAP, $oEmail, $s_Sent_Mailbox_Name)
			__Chilkat_LogOnError(@ScriptLineNumber & ' _Chilkat_EMAIL_SendSingleMail 6', $oMailMan)
			$iErr = @error
			$iExt = @extended
		EndIf
		$oIMAP.Disconnect()
	EndIf

	Local $iSuccess_CloseConnection = $oMailMan.CloseSmtpConnection()
	If $iErr Then Return SetError($iErr, $iExt, $vReturn)

	If @error Or $iSuccess_CloseConnection <> 1 Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber & ' MailMan.CloseSmtpConnection ', $oMailMan)
		Return SetError(@error, @extended, $iSuccess_CloseConnection)
	EndIf

	Return SetError(@error, @extended, $oEmail.GetMimeBinary())
EndFunc   ;==>_Chilkat_EMAIL_SendSingleMail

#EndRegion ; _Chilkat_EMAIL_**

#Region ; _Chilkat_Bounce_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Bounce_ObjCreate
; Description ...: Creates a Chilkat Bounce COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_Bounce_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Bounce object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatBounceRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_Bounce_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_BOUNCE)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_Bounce_ObjCreate

#EndRegion ; _Chilkat_Bounce_**

#Region ; _Chilkat_Dkim_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Dkim_ObjCreate
; Description ...: Creates a Chilkat Dkim COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_Dkim_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Dkim object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatDkimRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_Dkim_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_DKIM)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_Dkim_ObjCreate

#EndRegion ; _Chilkat_Dkim_**

#Region ; _Chilkat_EmailBundle_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_EmailBundle_ObjCreate
; Description ...: Creates a Chilkat EmailBundle COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_EmailBundle_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat EmailBundle object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatEmailBundleRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_EmailBundle_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_EMAILBUNDLE)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_EmailBundle_ObjCreate

#EndRegion ; _Chilkat_EmailBundle_**

#Region ; _Chilkat_MessageSet_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_MessageSet_ObjCreate
; Description ...: Creates a Chilkat MessageSet COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_MessageSet_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat MessageSet object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatMessageSetRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_MessageSet_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_MESSAGESET)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_MessageSet_ObjCreate

#EndRegion ; _Chilkat_MessageSet_**

#Region ; _Chilkat_Mht_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Mht_ObjCreate
; Description ...: Creates a Chilkat Mht COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_Mht_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Mht object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatMhtRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_Mht_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_MHT)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_Mht_ObjCreate

#EndRegion ; _Chilkat_Mht_**

#Region ; _Chilkat_Mime_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Mime_ObjCreate
; Description ...: Creates a Chilkat Mime COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_Mime_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Mime object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatMimeRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_Mime_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_MIME)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_Mime_ObjCreate

#EndRegion ; _Chilkat_Mime_**
