#include-once

#Region - Chilkat_DataFormats.au3 - Header
; Title .........: Chilkat_DataFormats.au3
; Language ......: English
; Description ...: Structured data, text conversion and encoding support.
; Author ........: mLipok
; Modified ......: AI / mLipok
; Date ..........: 2026/07/14
; Version .......: v0.3.0 BETA - Work in progress
; Remarks .......: This module is linked and loaded by Chilkat.au3.
; Categories ....: ASN.1; Base64; CSV; HTML-to-XML/Text; JSON; Markdown; XML
#EndRegion - Chilkat_DataFormats.au3 - Header

#Region - Chilkat_DataFormats.au3 - Object Functions
#Region ; _Chilkat_CSV_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_CSV_ObjCreate
; Description ...: Creates a Chilkat Csv COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_CSV_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Csv object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatCsvRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_CSV_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_CSV)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_CSV_ObjCreate

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_CSV_StringToArray
; Description ...: Parses CSV text with Chilkat CSV and returns a two-dimensional AutoIt array.
; Syntax ........: _Chilkat_CSV_StringToArray(ByRef $sCSVContent, $sDelimeter = @TAB, $iHasColumnNames = 1, $fnShowProgress = Default, $bEnableQuotes = 0)
; Parameters ....: $sCSVContent           - [in/out] CSV content string to parse.
;                  $sDelimeter            - [in] CSV delimiter character or string. Default is @TAB.
;                  $iHasColumnNames       - [in] flag indicating whether the first row contains column names. Default is 1.
;                  $fnShowProgress        - [in] optional progress callback called while rows are parsed. Default is Default.
;                  $bEnableQuotes         - [in] flag passed to Chilkat CSV EnableQuotes. Default is 0.
; Return values .: Success: two-dimensional array. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI - Returned array row 0 contains column names; data rows start at row 1.
; Related .......: _Chilkat_CSV_ObjCreate, __Chilkat_LogOnError
; Link ..........:
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_CSV_StringToArray(ByRef $sCSVContent, $sDelimeter = @TAB, $iHasColumnNames = 1, $fnShowProgress = Default, $bEnableQuotes = 0)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	Local $oCSV = _Chilkat_CSV_ObjCreate()
	If @error Then Return SetError(@error, @extended, $oCSV)

	;  Prior to loading the CSV file, indicate that the 1st row
	;  should be treated as column names:
	$oCSV.HasColumnNames = $iHasColumnNames
	__Chilkat_LogOnError(@ScriptLineNumber, $oCSV)
	$oCSV.Delimiter = $sDelimeter
	__Chilkat_LogOnError(@ScriptLineNumber, $oCSV)
	$oCSV.EnableQuotes = $bEnableQuotes
	__Chilkat_LogOnError(@ScriptLineNumber, $oCSV)

;~ 	If Not StringInStr($sDelimeter,'"') Then StringReplace($sCSVContent,'"','') ; @TODO temporary solution to fix bug which should be reported to chilkat

	; Load the $oCSV records from the file:
	Local $iSuccess = $oCSV.LoadFromString($sCSVContent)
	If @error Or ($iSuccess <> 1) Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber, $oCSV)
		Return SetError($CHILKAT_ERR_LOADFILE, @extended, $CHILKAT_RET_FAILURE)
	EndIf

	Local $iNumColumns = $oCSV.NumColumns
	Local $iNumRows = $oCSV.NumRows

	Local $aResult[$iNumRows + 1][$iNumColumns]

	; First get the column names
	For $iCol_idx = 0 To $iNumColumns - 1
		$aResult[0][$iCol_idx] = $oCSV.GetColumnName($iCol_idx)
	Next

	For $iRow_idx = 0 To $iNumRows - 1
		If IsFunc($fnShowProgress) Then $fnShowProgress($iRow_idx + 1, $iNumRows)
		For $iCol_idx = 0 To $iNumColumns - 1
			$aResult[$iRow_idx + 1][$iCol_idx] = $oCSV.GetCell($iRow_idx, $iCol_idx)
		Next
	Next

	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $aResult)
EndFunc   ;==>_Chilkat_CSV_StringToArray

#EndRegion ; _Chilkat_CSV_**

#Region ; _Chilkat_JSON_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_JSON_ObjCreate
; Description ...: Creates a Chilkat JsonObject COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_JSON_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat JsonObject object was introduced in version 9.5.0.56.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatJsonObjectRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_JSON_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_JSONOBJECT)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_JSON_ObjCreate

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_JSON_ObjFromString
; Description ...: Creates a Chilkat JsonObject and loads JSON text into it.
; Syntax ........: _Chilkat_JSON_ObjFromString(ByRef $sJSON_String, $iEmitCompact = 0, $iEmitCrLf = 1)
; Parameters ....: $sJSON_String          - [in/out] JSON string to load or format.
;                  $iEmitCompact          - [in] an integer value. Default is 0.
;                  $iEmitCrLf             - [in] an integer value. Default is 1.
; Return values .: Success: Chilkat JsonObject. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: _Chilkat_JSON_ObjCreate, __Chilkat_LogOnError
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_JSON_ObjFromString(ByRef $sJSON_String, $iEmitCompact = 0, $iEmitCrLf = 1)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	Local $oJSON = _Chilkat_JSON_ObjCreate()
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	Local $iSuccess = $oJSON.Load($sJSON_String)
	If @error Or ($iSuccess <> 1) Then
		If Not @error Then SetError($CHILKAT_ERR_FAILURE, @extended)
		__Chilkat_LogOnError(@ScriptLineNumber, $oJSON)
		Return SetError($CHILKAT_ERR_LOAD, @extended, $CHILKAT_RET_FAILURE)
	EndIf

	;  To pretty-print, set the EmitCompact property equal to 0
	$oJSON.EmitCompact = $iEmitCompact

	;  If bare-LF line endings are desired, turn off EmitCrLf
	;  Otherwise CRLF line endings are emitted.
	$oJSON.EmitCrLf = $iEmitCrLf

	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oJSON)

EndFunc   ;==>_Chilkat_JSON_ObjFromString

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_JSON_ObjToString
; Description ...: Serializes a Chilkat JsonObject to a JSON string.
; Syntax ........: _Chilkat_JSON_ObjToString(ByRef $oJSON, $iEmitCompact = 0, $iEmitCrLf = 1)
; Parameters ....: $oJSON                 - [in/out] Chilkat JsonObject object.
;                  $iEmitCompact          - [in] an integer value. Default is 0.
;                  $iEmitCrLf             - [in] an integer value. Default is 1.
; Return values .: Success: JSON string. Failure: sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......:
; Link ..........:
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_JSON_ObjToString(ByRef $oJSON, $iEmitCompact = 0, $iEmitCrLf = 1)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	If Not IsObj($oJSON) Then Return SetError(1) ; @TODO Error handling

	;  To pretty-print, set the EmitCompact property equal to 0
	$oJSON.EmitCompact = $iEmitCompact

	;  If bare-LF line endings are desired, turn off EmitCrLf
	;  Otherwise CRLF line endings are emitted.
	$oJSON.EmitCrLf = $iEmitCrLf

	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oJSON.Emit())

EndFunc   ;==>_Chilkat_JSON_ObjToString

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_JSON_StringPretty
; Description ...: Returns a formatted JSON string from a JSON input string.
; Syntax ........: _Chilkat_JSON_StringPretty(ByRef $sJSON_String)
; Parameters ....: $sJSON_String          - [in/out] JSON string to load or format.
; Return values .: Success: formatted JSON string. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Header generated by #AI
; Related .......: _Chilkat_JSON_ObjFromString
; Link ..........:
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_JSON_StringPretty(ByRef $sJSON_String)
	Local $oErrorHandler = ObjEvent("AutoIt.Error", __Internal_COM_ERROR_HANDLER__for_Chilkat)
	#forceref $oErrorHandler

	Local $oJSON = _Chilkat_JSON_ObjFromString($sJSON_String)
	If @error Then Return SetError(@error, @extended, $CHILKAT_RET_FAILURE)

	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oJSON.Emit())
EndFunc   ;==>_Chilkat_JSON_StringPretty

#EndRegion ; _Chilkat_JSON_**

#Region ; _Chilkat_XML_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_XML_ObjCreate
; Description ...: Creates a Chilkat Xml COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_XML_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Xml object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatXmlRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_XML_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_XML)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_XML_ObjCreate

#EndRegion ; _Chilkat_XML_**

#Region ; _Chilkat_CKSTRING_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_CKSTRING_ObjCreate
; Description ...: Creates a Chilkat CkString COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_CKSTRING_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat CkString object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatCkStringRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_CKSTRING_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_CKSTRING)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_CKSTRING_ObjCreate

#EndRegion ; _Chilkat_CKSTRING_**

#Region ; _Chilkat_StringBuilder_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_StringBuilder_ObjCreate
; Description ...: Creates a Chilkat StringBuilder COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_StringBuilder_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat StringBuilder object was introduced in version 9.5.0.58.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatStringBuilderRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_StringBuilder_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_STRINGBUILDER)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_StringBuilder_ObjCreate

#EndRegion ; _Chilkat_StringBuilder_**

#Region ; _Chilkat_Asn_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Asn_ObjCreate
; Description ...: Creates a Chilkat Asn COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_Asn_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat Asn object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatAsnRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_Asn_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_ASN)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_Asn_ObjCreate

#EndRegion ; _Chilkat_Asn_**

#Region ; _Chilkat_HtmlToText_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_HtmlToText_ObjCreate
; Description ...: Creates a Chilkat HtmlToText COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_HtmlToText_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat HtmlToText object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatHtmlToTextRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_HtmlToText_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_HTMLTOTEXT)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_HtmlToText_ObjCreate

#EndRegion ; _Chilkat_HtmlToText_**

#Region ; _Chilkat_HtmlToXml_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_HtmlToXml_ObjCreate
; Description ...: Creates a Chilkat HtmlToXml COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_HtmlToXml_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat HtmlToXml object was introduced in version 9.5.0.44.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatHtmlToXmlRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_HtmlToXml_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_HTMLTOXML)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_HtmlToXml_ObjCreate

#EndRegion ; _Chilkat_HtmlToXml_**

#Region ; _Chilkat_JsonArray_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_JsonArray_ObjCreate
; Description ...: Creates a Chilkat JsonArray COM object for the selected Chilkat API version.
; Syntax ........: _Chilkat_JsonArray_ObjCreate()
; Parameters ....: None
; Return values .: Success: Chilkat COM object. Failure: $CHILKAT_RET_FAILURE and sets @error/@extended.
; Author ........: mLipok
; Modified ......:
; Remarks .......: Chilkat JsonArray object was introduced in version 9.5.0.56.
;                  Uses ChilkatConstants.au3 object metadata through __Chilkat_ObjCreate_Wrapper().
; Related .......: __Chilkat_ObjCreate_Wrapper
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatJsonArrayRef.html
; Example .......: No
; ===============================================================================================================================
Func _Chilkat_JsonArray_ObjCreate()
	Local $oObject = __Chilkat_ObjCreate_Wrapper($CHILKATOBJ_NAME_JSONARRAY)
	Return SetError(@error, @extended, $oObject)
EndFunc   ;==>_Chilkat_JsonArray_ObjCreate

#EndRegion ; _Chilkat_JsonArray_**


#Region ; _Chilkat_Base64_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Base64_EncodeString
; Description ...: Encodes a text string as Base64 or Base64URL.
; Syntax ........: _Chilkat_Base64_EncodeString($sText, $sCharset = 'utf-8', $bUrlSafe = 0)
; Parameters ....: $sText                 - [in] text to encode.
;                  $sCharset              - [in] character encoding used before Base64 encoding. Default is utf-8.
;                  $bUrlSafe              - [in] when 1, uses Base64URL. Default is 0.
; Return values .: Success: encoded string. Failure: empty string and sets @error/@extended.
; Author ........: AI / mLipok
; Modified ......:
; Remarks .......: Uses Chilkat StringBuilder.Encode().
; Related .......: _Chilkat_Base64_DecodeString, _Chilkat_StringBuilder_ObjCreate
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatStringBuilderRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_Base64_EncodeString($sText, $sCharset = 'utf-8', $bUrlSafe = 0)
	If Not IsString($sText) Then Return SetError($CHILKAT_ERR_INVALIDPARAMETERTYPE, $CHILKAT_EXT_PARAM1, '')
	If Not IsString($sCharset) Or $sCharset = '' Then Return SetError($CHILKAT_ERR_INVALIDPARAMETERVALUE, $CHILKAT_EXT_PARAM2, '')
	Local $oSb = _Chilkat_StringBuilder_ObjCreate()
	If @error Then Return SetError(@error, @extended, '')
	$oSb.SetString($sText)
	Local $sEncoding = $bUrlSafe ? 'base64url' : 'base64'
	Local $iSuccess = $oSb.Encode($sEncoding, $sCharset)
	If $iSuccess = 0 Then Return SetError($CHILKAT_ERR_FAILURE, $CHILKAT_EXT_GENERAL, '')
	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oSb.GetAsString())
EndFunc   ;==>_Chilkat_Base64_EncodeString

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Base64_DecodeString
; Description ...: Decodes Base64 or Base64URL text to a string.
; Syntax ........: _Chilkat_Base64_DecodeString($sEncodedText, $sCharset = 'utf-8', $bUrlSafe = 0)
; Parameters ....: $sEncodedText          - [in] Base64/Base64URL text.
;                  $sCharset              - [in] character encoding of decoded bytes. Default is utf-8.
;                  $bUrlSafe              - [in] when 1, decodes Base64URL. Default is 0.
; Return values .: Success: decoded string. Failure: empty string and sets @error/@extended.
; Author ........: AI / mLipok
; Modified ......:
; Remarks .......: Uses Chilkat StringBuilder.Decode().
; Related .......: _Chilkat_Base64_EncodeString, _Chilkat_StringBuilder_ObjCreate
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatStringBuilderRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_Base64_DecodeString($sEncodedText, $sCharset = 'utf-8', $bUrlSafe = 0)
	If Not IsString($sEncodedText) Then Return SetError($CHILKAT_ERR_INVALIDPARAMETERTYPE, $CHILKAT_EXT_PARAM1, '')
	If Not IsString($sCharset) Or $sCharset = '' Then Return SetError($CHILKAT_ERR_INVALIDPARAMETERVALUE, $CHILKAT_EXT_PARAM2, '')
	Local $oSb = _Chilkat_StringBuilder_ObjCreate()
	If @error Then Return SetError(@error, @extended, '')
	$oSb.SetString($sEncodedText)
	Local $sEncoding = $bUrlSafe ? 'base64url' : 'base64'
	Local $iSuccess = $oSb.Decode($sEncoding, $sCharset)
	If $iSuccess = 0 Then Return SetError($CHILKAT_ERR_FAILURE, $CHILKAT_EXT_GENERAL, '')
	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oSb.GetAsString())
EndFunc   ;==>_Chilkat_Base64_DecodeString

#EndRegion ; _Chilkat_Base64_**

#Region ; _Chilkat_Markdown_**

; #FUNCTION# ====================================================================================================================
; Name ..........: _Chilkat_Markdown_ToHtml
; Description ...: Converts Markdown text to HTML by using Chilkat StringBuilder.MarkdownToHtml().
; Syntax ........: _Chilkat_Markdown_ToHtml($sMarkdown, $oOptions = Default)
; Parameters ....: $sMarkdown             - [in] Markdown source text.
;                  $oOptions              - [in] optional Chilkat JsonObject options. Default uses non-streaming raw HTML output.
; Return values .: Success: HTML string. Failure: empty string and sets @error/@extended.
; Author ........: AI / mLipok
; Modified ......:
; Remarks .......: Requires Chilkat 11.2.0 or newer.
; Related .......: _Chilkat_StringBuilder_ObjCreate, _Chilkat_JSON_ObjCreate
; Link ..........: https://www.chilkatsoft.com/refdoc/xChilkatStringBuilderRef.html
; Example .......: Yes
; ===============================================================================================================================
Func _Chilkat_Markdown_ToHtml($sMarkdown, $oOptions = Default)
	If Not IsString($sMarkdown) Then Return SetError($CHILKAT_ERR_INVALIDPARAMETERTYPE, $CHILKAT_EXT_PARAM1, '')
	If Not _Chilkat_IsAtLeastThisVersion('11.2.0', 'StringBuilder.MarkdownToHtml') Then _
			Return SetError($CHILKAT_ERR_FAILURE, $CHILKAT_EXT_GENERAL, '')

	Local $oSource = _Chilkat_StringBuilder_ObjCreate()
	If @error Then Return SetError(@error, @extended, '')
	Local $oHtml = _Chilkat_StringBuilder_ObjCreate()
	If @error Then Return SetError(@error, @extended, '')
	Local $oEffectiveOptions = $oOptions
	If $oEffectiveOptions = Default Then
		$oEffectiveOptions = _Chilkat_JSON_ObjCreate()
		If @error Then Return SetError(@error, @extended, '')
		$oEffectiveOptions.UpdateBool('streaming', False)
		$oEffectiveOptions.UpdateString('theme', 'raw')
	ElseIf Not IsObj($oEffectiveOptions) Then
		Return SetError($CHILKAT_ERR_ISNOTOBJ, $CHILKAT_EXT_PARAM2, '')
	EndIf

	$oSource.SetString($sMarkdown)
	Local $iSuccess = $oSource.MarkdownToHtml($oEffectiveOptions, $oHtml)
	If $iSuccess = 0 Then Return SetError($CHILKAT_ERR_FAILURE, $CHILKAT_EXT_GENERAL, '')
	Return SetError($CHILKAT_ERR_SUCCESS, $CHILKAT_EXT_DEFAULT, $oHtml.GetAsString())
EndFunc   ;==>_Chilkat_Markdown_ToHtml

#EndRegion ; _Chilkat_Markdown_**

#EndRegion - Chilkat_DataFormats.au3 - Object Functions
